name: release

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Build Release
        run: |
          mkdir -p bin
          for arch in i686 x86_64 arm armhf aarch64 mips mipsel mips64 mips64el; do
            ./scripts/cross-build.sh $arch
            cp build/ttyd bin/ttyd_linux.$arch
            sha256sum bin/ttyd_linux.$arch >> bin/SHA256SUMS
          done
      - uses: ncipollo/release-action@v1
        with:
          artifact: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
